#!/usr/bin/env bash

ssh() {
    echo "Connecting to workspace.."
    docker-compose exec php bash
}

up() {
    echo "Bringing up docker containers.."
    docker-compose up -d --build
}

down() {
    echo "Bringing down docker containers.."
    docker-compose down
}

restart() {
    echo "Rebooting docker containers.."
    down
    up
}

if [[ -n "$1" ]]; then
    command="$1"
    if [[ -n "$(type -t "${command}")" ]] && [[ "$(type -t "${command}")" == function ]]; then
        "$command" "${@:2}"
        exit
    fi
fi

echo "Command not found"
exit
